# Generated by Django 4.0.3 on 2022-04-13 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='company_name',
            field=models.CharField(default='Default Company', max_length=100, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Posted'),
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='Name', max_length=100, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='Name', max_length=100, verbose_name='Last Name'),
        ),
    ]
