# Generated by Django 4.0.3 on 2022-04-13 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contact_name_remove_contact_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Posted'),
        ),
    ]
