# Generated by Django 4.0.3 on 2022-04-13 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_remove_event_subject_event_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='techrequest',
            name='request_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Request Date'),
        ),
        migrations.AlterField(
            model_name='techrequest',
            name='message',
            field=models.TextField(default='I would like to request for this technology', verbose_name='Message'),
        ),
    ]
