# Generated by Django 4.0.3 on 2022-04-13 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_techrequest_request_data_alter_techrequest_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techrequest',
            old_name='request_data',
            new_name='request_date',
        ),
    ]
