# Generated by Django 4.0.3 on 2022-04-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_rename_request_data_techrequest_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techrequest',
            name='message',
            field=models.TextField(default='I would like to request this technology', verbose_name='Message'),
        ),
    ]
