# Generated by Django 4.0.3 on 2022-04-25 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_techrequest_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
