# Generated by Django 4.0.3 on 2022-04-15 08:06

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', django_resized.forms.ResizedImageField(crop=['top', 'left'], force_format=None, keep_meta=True, quality=0, size=[400, 300], upload_to='photo/')),
            ],
        ),
    ]
