# Generated by Django 4.0.3 on 2022-04-11 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Technology Name')),
                ('short_description', models.CharField(max_length=250, verbose_name='Short Description')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Posted')),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d', verbose_name='Upload Image')),
            ],
            options={
                'ordering': ('-date_posted',),
            },
        ),
    ]
