# Generated by Django 4.0.3 on 2022-04-14 02:30

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0002_arraytest'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='details_list',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=400), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='arraytest',
            name='tags',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=300), size=None),
        ),
    ]
