# Generated by Django 4.0.3 on 2022-04-14 02:48

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0003_technology_details_list_alter_arraytest_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArrayTest',
        ),
        migrations.AlterField(
            model_name='technology',
            name='details_list',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=400), size=None),
        ),
    ]
