# Generated by Django 4.0.3 on 2022-04-14 02:52

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0004_delete_arraytest_alter_technology_details_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='details_list',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=400), blank=True, null=True, size=None),
        ),
    ]
