# Generated by Django 4.0.3 on 2022-04-15 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0007_presenter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Presenter',
        ),
    ]
